### PR TITLE
chore(main): release 0.2.5

### LINKED ISSUE #33: rustler_precompiled ~> 0.7 constraint too loose — 0.2.3 requires 0.8.0+
`mdex_native` 0.2.3's `mix.exs` declares `{:rustler_precompiled, "~> 0.7"}`, but 0.2.3 changed `native.ex` to pass a `{module, function}` tuple as base_url (`{MDExNative.Native.ArtifactURL, :url}`), which is only supported from `rustler_precompiled` **0.8.0** onward. 

Trying to compile with `rustler_precompiled` 0.7.3 (because another dependency has that hard requirement) throws this error:

```elixir
> == Compilation error in file lib/mdex_native/native.ex ==
> ** (FunctionClauseError) no function clause matching in :uri_string.parse/1
>
>     The following arguments were given to :uri_string.parse/1:
>
>         # 1
>         {MDExNative.Native.ArtifactURL, :url}
>
>     (stdlib 8.0.1) :uri_string.parse/1
>     (rustler_precompiled 0.7.3) lib/rustler_precompiled/config.ex:87: RustlerPrecompiled.Config.validate_base_url!/1
>     (rustler_precompiled 0.7.3) lib/rustler_precompiled/config.ex:45: RustlerPrecompiled.Config.new/1
>     (rustler_precompiled 0.7.3) lib/rustler_precompiled.ex:204: RustlerPrecompiled.__using__/2
>     lib/mdex_native/native.ex:97: (module)
```

### PR DESCRIPTION
**Pull request by leandrocp**
:robot: I have created a release *beep* *boop*
---

### Features

* update comrak v0.53 ([#40](https://github.com/leandrocp/mdex_native/issues/40)) ([7e239ba](https://github.com/leandrocp/mdex_native/commit/7e239ba01ca72190119a5c473ef0f13add150fae))
* Reduce comrak features to only ones used by @josevalim

### Bug Fixes

* bump minimum rustler_precompiled ([#37](https://github.com/leandrocp/mdex_native/issues/37)) ([36bd51c](https://github.com/leandrocp/mdex_native/commit/36bd51c809b9107ba2e2eb373b7f024064ba1f2d)), closes [#33](https://github.com/leandrocp/mdex_native/issues/33)
* render attrs on pre tag for html multi themes formatter ([#39](https://github.com/leandrocp/mdex_native/issues/39)) ([05204c9](https://github.com/leandrocp/mdex_native/commit/05204c9b3e532ca555746e45a5bddd7bcb1d379d))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by leandrocp** [comment]
🤖 Created releases:

- [v0.2.5](https://github.com/leandrocp/mdex_native/releases/tag/v0.2.5)

:sunflower:
