### ISSUE TITLE
rustler_precompiled ~> 0.7 constraint too loose — 0.2.3 requires 0.8.0+

### ISSUE THREAD

**Issue by moomerman** [leandrocp/mdex_native#33]
`mdex_native` 0.2.3's `mix.exs` declares `{:rustler_precompiled, "~> 0.7"}`, but 0.2.3 changed `native.ex` to pass a `{module, function}` tuple as base_url (`{MDExNative.Native.ArtifactURL, :url}`), which is only supported from `rustler_precompiled` **0.8.0** onward. 

Trying to compile with `rustler_precompiled` 0.7.3 (because another dependency has that hard requirement) throws this error:

```elixir
> == Compilation error in file lib/mdex_native/native.ex ==
> ** (FunctionClauseError) no function clause matching in :uri_string.parse/1
>
>     The following arguments were given to :uri_string.parse/1:
>
>         # 1
>         {MDExNative.Native.ArtifactURL, :url}
>
>     (stdlib 8.0.1) :uri_string.parse/1
>     (rustler_precompiled 0.7.3) lib/rustler_precompiled/config.ex:87: RustlerPrecompiled.Config.validate_base_url!/1
>     (rustler_precompiled 0.7.3) lib/rustler_precompiled/config.ex:45: RustlerPrecompiled.Config.new/1
>     (rustler_precompiled 0.7.3) lib/rustler_precompiled.ex:204: RustlerPrecompiled.__using__/2
>     lib/mdex_native/native.ex:97: (module)
```

**Comment by leandrocp** [comment]
Thanks @moomerman a new version will be released shortly
